[window]
padding = { x = 10, y = 10 }
decorations = "Full" #none geht leider nicht so gut fuer daily usage
decorations_theme_variant = "Dark"

[shell]
args = ['pwsh']
program = "wsl"


[cursor]
style.shape = "Beam"
style.blinking = "On"

[font] 
size = 13.0
offset = { x = 0, y = 0 }

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[colors]
# transparent_background_colors = true
#selection = { text = "CellForeground", background = "#BDBDBD" }
selection = { text = "CellBackground", background = "#FFFFFF" }

[colors.primary]
foreground = "#CCCCCC"
background = "#012456"

[colors.normal]
black = "#0C0C0C"
red = "#C50F1F"
green = "#13A10E"
yellow = "#C19C00"
blue = "#0037DA"
magenta = "#881798"
cyan = "#3A96DD"
white = "#CCCCCC"

[colors.bright]
black = "#767676"
red = "#E74856"
green = "#16C60C"
yellow = "#F9F1A5"
blue = "#3B78FF"
magenta = "#B4009E"
cyan = "#61D6D6"
white = "#F2F2F2"

[selection]
save_to_clipboard = true
